name: Sync Dependencies

on:
  schedule:
    - cron: "0 6 * * *" # daily
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Sync dependencies
        run: |
          uv run -q python scripts/sync_dependencies.py --check
